# Generated by Django 6.1.1 on 2026-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contact', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('booking_url', models.URLField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='pending', max_length=10)),
            ],
        ),
    ]
