# Generated by Django 6.1.1 on 2026-09-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
